# /etc/profile.d/gnome-proxy.sh                                                                                                                                                                                                                                              
# Sync GNOME "Network Proxy" (org.gnome.system.proxy, mode=manual) into the                                                                                                                                                                                                  
# http_proxy / https_proxy / all_proxy / no_proxy environment variables so that                                                                                                                                                                                              
# CLI tools (curl, git, pip, dnf, cargo, ...) launched in the terminal honor it.                                                                                                                                                                                             
# Runs once per interactive shell start. Only acts when mode=manual.                                                                                                                                                                                                         

# Respect an explicit override: if any of these are already set, do nothing.                                                                                                                                                                                                 
case ":$http_proxy$https_proxy$all_proxy:" in                                                                                                                                                                                                                                
  *:?*:) return 0 2>/dev/null || exit 0 ;;                                                                                                                                                                                                                                   
esac                                                                                                                                                                                                                                                                         

command -v gsettings >/dev/null 2>&1 || return 0 2>/dev/null || exit 0                                                                                                                                                                                                       

# Only meaningful inside a graphical GNOME session.                                                                                                                                                                                                                          
case "${XDG_CURRENT_DESKTOP:-}" in *GNOME*) ;; *) return 0 2>/dev/null || exit 0 ;; esac                                                                                                                                                                                     

mode=$(gsettings get org.gnome.system.proxy mode 2>/dev/null)                                                                                                                                                                                                                
# strip surrounding single quotes: 'manual' -> manual                                                                                                                                                                                                                        
mode=${mode#\'}; mode=${mode%\'}                                                                                                                                                                                                                                             
[ "$mode" = "manual" ] || return 0 2>/dev/null || exit 0                                                                                                                                                                                                                     

_gp_get() {  # $1=schema-child $2=key  -> prints value or nothing                                                                                                                                                                                                            
    v=$(gsettings get "org.gnome.system.proxy.$1" "$2" 2>/dev/null)                                                                                                                                                                                                          
    v=${v#\'}; v=${v%\'}                                                                                                                                                                                                                                                     
    [ "$v" != "none" ] && [ -n "$v" ] && printf '%s' "$v"                                                                                                                                                                                                                    
}                                                                                                                                                                                                                                                                            

_h=$(_gp_get http host); _p=$(_gp_get http port)                                                                                                                                                                                                                             
[ -n "$_h" ] && [ -n "$_p" ] && export http_proxy="http://$_h:$_p" HTTP_PROXY="http://$_h:$_p"                                                                                                                                                                               

_h=$(_gp_get https host); _p=$(_gp_get https port)                                                                                                                                                                                                                           
[ -n "$_h" ] && [ -n "$_p" ] && export https_proxy="http://$_h:$_p" HTTPS_PROXY="http://$_h:$_p"                                                                                                                                                                             

_h=$(_gp_get socks host); _p=$(_gp_get socks port)                                                                                                                                                                                                                           
[ -n "$_h" ] && [ -n "$_p" ] && export all_proxy="socks5h://$_h:$_p" ALL_PROXY="socks5h://$_h:$_p"                                                                                                                                                                           

# ignore-hosts -> no_proxy. gsettings returns: @as ['a','b']  or  @as []                                                                                                                                                                                                     
_nop=$(gsettings get org.gnome.system.proxy ignore-hosts 2>/dev/null)                                                                                                                                                                                                        
_nop=${_nop#@as }; _nop=${_nop#[}; _nop=${_nop%]}; _nop=${_nop//\'/}                                                                                                                                                                                                         
_nop=${_nop//,/,}                                                                                                                                                                                                                                                            
[ -n "$_nop" ] && export no_proxy="$_nop" NO_PROXY="$_nop"                                                                                                                                                                                                                   

unset -f _gp_get                                                                                                                                                                                                                                                             
unset _h _p _nop mode
