# /etc/profile.d/gnome-proxy.sh                                                                                                                                                                                                                                              
# Keep the http_proxy / https_proxy / all_proxy / no_proxy environment variables                                                                                                                                                                                             
# in sync with GNOME "Network Proxy" (org.gnome.system.proxy).                                                                                                                                                                                                               
#   mode = manual  -> populate from GNOME settings                                                                                                                                                                                                                           
#   mode = none/auto -> unset them                                                                                                                                                                                                                                           
# Runs once per interactive shell start. Reflects whatever GNOME shows *now*,                                                                                                                                                                                                
# so re-sourcing (or opening a new Ghostty window) after changing the setting                                                                                                                                                                                                
# picks up the new state, including clearing the vars when proxy is disabled.                                                                                                                                                                                                

command -v gsettings >/dev/null 2>&1 || return 0 2>/dev/null || exit 0                                                                                                                                                                                                       

# Only meaningful inside a graphical GNOME session.                                                                                                                                                                                                                          
case "${XDG_CURRENT_DESKTOP:-}" in *GNOME*) ;; *) return 0 2>/dev/null || exit 0 ;; esac                                                                                                                                                                                     

mode=$(gsettings get org.gnome.system.proxy mode 2>/dev/null)                                                                                                                                                                                                                
# strip surrounding single quotes: 'manual' -> manual                                                                                                                                                                                                                        
mode=${mode#\'}; mode=${mode%\'}                                                                                                                                                                                                                                             

if [ "$mode" != "manual" ]; then                                                                                                                                                                                                                                             
    unset http_proxy HTTP_PROXY https_proxy HTTPS_PROXY all_proxy ALL_PROXY no_proxy NO_PROXY                                                                                                                                                                                
    unset mode                                                                                                                                                                                                                                                               
    return 0 2>/dev/null || exit 0                                                                                                                                                                                                                                           
fi                                                                                                                                                                                                                                                                           

_gp_get() {  # $1=schema-child $2=key  -> prints value or nothing                                                                                                                                                                                                            
    v=$(gsettings get "org.gnome.system.proxy.$1" "$2" 2>/dev/null)                                                                                                                                                                                                          
    v=${v#\'}; v=${v%\'}                                                                                                                                                                                                                                                     
    [ "$v" != "none" ] && [ -n "$v" ] && printf '%s' "$v"                                                                                                                                                                                                                    
}                                                                                                                                                                                                                                                                            

_h=$(_gp_get http host); _p=$(_gp_get http port)                                                                                                                                                                                                                             
if [ -n "$_h" ] && [ -n "$_p" ]; then                                                                                                                                                                                                                                        
    export http_proxy="http://$_h:$_p" HTTP_PROXY="http://$_h:$_p"                                                                                                                                                                                                           
else                                                                                                                                                                                                                                                                         
    unset http_proxy HTTP_PROXY                                                                                                                                                                                                                                              
fi                                                                                                                                                                                                                                                                           

_h=$(_gp_get https host); _p=$(_gp_get https port)                                                                                                                                                                                                                           
if [ -n "$_h" ] && [ -n "$_p" ]; then                                                                                                                                                                                                                                        
    export https_proxy="http://$_h:$_p" HTTPS_PROXY="http://$_h:$_p"                                                                                                                                                                                                         
else                                                                                                                                                                                                                                                                         
    unset https_proxy HTTPS_PROXY                                                                                                                                                                                                                                            
fi                                                                                                                                                                                                                                                                           

_h=$(_gp_get socks host); _p=$(_gp_get socks port)                                                                                                                                                                                                                           
if [ -n "$_h" ] && [ -n "$_p" ]; then                                                                                                                                                                                                                                        
    export all_proxy="socks5h://$_h:$_p" ALL_PROXY="socks5h://$_h:$_p"                                                                                                                                                                                                       
else                                                                                                                                                                                                                                                                         
    unset all_proxy ALL_PROXY                                                                                                                                                                                                                                                
fi                                                                                                                                                                                                                                                                           

# ignore-hosts -> no_proxy. gsettings returns: @as ['a','b']  or  @as []                                                                                                                                                                                                     
_nop=$(gsettings get org.gnome.system.proxy ignore-hosts 2>/dev/null)                                                                                                                                                                                                        
_nop=${_nop#@as }; _nop=${_nop#[}; _nop=${_nop%]}; _nop=${_nop//\'/}                                                                                                                                                                                                         
_nop=${_nop//,/,}                                                                                                                                                                                                                                                            
if [ -n "$_nop" ]; then                                                                                                                                                                                                                                                      
    export no_proxy="$_nop" NO_PROXY="$_nop"                                                                                                                                                                                                                                 
else                                                                                                                                                                                                                                                                         
    unset no_proxy NO_PROXY                                                                                                                                                                                                                                                  
fi                                                                                                                                                                                                                                                                           

unset -f _gp_get                                                                                                                                                                                                                                                             
unset _h _p _nop mode
